version: "3"

services:
  nuxt:
    build: ./app/
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm run start"

  nginx:
    build: ./nginx/
    ports:
      - "81:81"
      - 441:441
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt
      
