version: '3'
services:
  #======================================================================  app server  ======
  rails:
    # restart: always
    build:
      context: ./rails
      args:
        - ENV=${ENV}
        - APP_NAME=${APP_NAME}
        - ROOT_PASSWORD=${ROOT_PASSWORD}
        - USER_NAME=${USER_NAME}
        - USER_PASSWORD=${USER_PASSWORD}
    working_dir: /opt/${APP_NAME}
    # just wake up container
    command: /bin/sh -c "while sleep 1000; do :; done"
    # new application
    # command: bundle config set path 'vendor/bundle' && bundle install && yarn install --check-files
    # cloned application
    # command: bundle install && yarn install --check-files
    # start application server
    # command: bundle exec puma -C config/puma.rb
    # expose:
      # - "8001"
    volumes:
      - ./${APP_NAME}:/opt/${APP_NAME}
      - web_app_socket:${WEB_APP_SOCKET}
      - app_db_socket:/var/run/mysqld
    depends_on:
      - mysql
  #======================================================================  web server  ======
  nginx:
    build:
      context: ./nginx
    # ports:
      # - 3000:3000
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
      - web_app_socket:${WEB_APP_SOCKET}
      # - ./static:/static
    depends_on:
      - rails
  #======================================================================  db  ======
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    # ports:
      # - 3306:3306
    volumes:
      # - ./mysql/data:/var/lib/mysql
      - db_data:/var/lib/mysql
      - app_db_socket:/var/run/mysqld
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      # - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    hostname: db
volumes:
  web_app_socket:
  app_db_socket:
  db_data:
